name: Context testing
on: 
  push:
    branches: ["main"]
    paths:
      - "subproject/context.txt"

jobs:
  dump_contexts_to_log:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context object
        id: github_context_step_obj
        run: echo '${{ github }}'
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump secrets context
        run: echo '${{ toJSON(secrets) }}'

  dump_field_to_log:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - name: Echo pull req
        run: echo '****** Pull: This was a ${{ github.event }} ********'

  dump_another_field_to_log:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Echo push
        run: echo '****** Push:  This was a ${{ github.event }} ********'
