name: Stg Deployment
on: 
  push:
    branches: [ 'main' ]
    paths:
      - 'subproject/environment.txt'
env:
  mySecret: ${{secrets.STG_SECRET}}

jobs:

  deployment:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: deploy
        run: |
          echo "Stg var is ${{vars.STG_VAR}}"
          echo "Stg secret 1 is ${{env.mySecret}}"
          echo "Stg secret 2 is "
          echo ${{env.mySecret}}" | sed 's/./& /g'
          echo "Stg secret 3 is "
          echo ${{secrets.STG_SECRET}} | sed 's/./& /g'
